import type { Metadata } from "next";
import { Geist, Geist_Mono, Slabo_13px } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const slabo13px = Slabo_13px({
  variable: "--font-slabo-13px",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${slabo13px.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
